// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerApi.Data;

#nullable disable

namespace TaskManagerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325181928_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerApi.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colaboradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "pam@example.com",
                            Nome = "Pam",
                            Senha = "senha123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jim@example.com",
                            Nome = "Jim",
                            Senha = "senha456"
                        },
                        new
                        {
                            Id = 3,
                            Email = "kevin@example.com",
                            Nome = "Kevin",
                            Senha = "senha789"
                        },
                        new
                        {
                            Id = 4,
                            Email = "kelly@example.com",
                            Nome = "Kelly",
                            Senha = "senha012"
                        },
                        new
                        {
                            Id = 5,
                            Email = "dwight@example.com",
                            Nome = "Dwight",
                            Senha = "senha345"
                        },
                        new
                        {
                            Id = 6,
                            Email = "michael@example.com",
                            Nome = "Michael",
                            Senha = "senha678"
                        },
                        new
                        {
                            Id = 7,
                            Email = "angela@example.com",
                            Nome = "Angela",
                            Senha = "senha901"
                        },
                        new
                        {
                            Id = 8,
                            Email = "stanley@example.com",
                            Nome = "Stanley",
                            Senha = "senha234"
                        },
                        new
                        {
                            Id = 9,
                            Email = "oscar@example.com",
                            Nome = "Oscar",
                            Senha = "senha567"
                        },
                        new
                        {
                            Id = 10,
                            Email = "phyllis@example.com",
                            Nome = "Phyllis",
                            Senha = "senha890"
                        });
                });

            modelBuilder.Entity("TaskManagerApi.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColaboradorId = 1,
                            DataCriacao = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 1",
                            Status = 0,
                            Titulo = "Alimentar o cachorro"
                        },
                        new
                        {
                            Id = 2,
                            ColaboradorId = 2,
                            DataCriacao = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 2",
                            Status = 1,
                            Titulo = "Fazer compras"
                        },
                        new
                        {
                            Id = 3,
                            ColaboradorId = 3,
                            DataCriacao = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 3",
                            Status = 2,
                            Titulo = "Ir à padaria"
                        },
                        new
                        {
                            Id = 4,
                            ColaboradorId = 4,
                            DataCriacao = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 4",
                            Status = 0,
                            Titulo = "Ir à feira"
                        },
                        new
                        {
                            Id = 5,
                            ColaboradorId = 5,
                            DataCriacao = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 5",
                            Status = 1,
                            Titulo = "Comprar itens de festa"
                        },
                        new
                        {
                            Id = 6,
                            ColaboradorId = 6,
                            DataCriacao = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 6",
                            Status = 2,
                            Titulo = "Contratar palhaço"
                        },
                        new
                        {
                            Id = 7,
                            ColaboradorId = 7,
                            DataCriacao = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 7",
                            Status = 0,
                            Titulo = "Limpar o escritório"
                        },
                        new
                        {
                            Id = 8,
                            ColaboradorId = 8,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 8",
                            Status = 1,
                            Titulo = "Preparar a festa"
                        },
                        new
                        {
                            Id = 9,
                            ColaboradorId = 1,
                            DataCriacao = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 9",
                            Status = 2,
                            Titulo = "Preparar comida"
                        },
                        new
                        {
                            Id = 10,
                            ColaboradorId = 2,
                            DataCriacao = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 10",
                            Status = 0,
                            Titulo = "Preparar decoração"
                        },
                        new
                        {
                            Id = 11,
                            ColaboradorId = 3,
                            DataCriacao = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 11",
                            Status = 1,
                            Titulo = "Comer"
                        },
                        new
                        {
                            Id = 12,
                            ColaboradorId = 4,
                            DataCriacao = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição da tarefa 12",
                            Status = 2,
                            Titulo = "Fofocar"
                        });
                });

            modelBuilder.Entity("TaskManagerApi.Models.Tarefa", b =>
                {
                    b.HasOne("TaskManagerApi.Models.Colaborador", "Colaborador")
                        .WithMany("Tarefas")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("TaskManagerApi.Models.Colaborador", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
